################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../UR_code/developer_code/tests\ src/dac_adc_test.c \
../UR_code/developer_code/tests\ src/flash_test.c \
../UR_code/developer_code/tests\ src/i2c_test.c \
../UR_code/developer_code/tests\ src/spi_test.c \
../UR_code/developer_code/tests\ src/uart_test.c 

OBJS += \
./UR_code/developer_code/tests\ src/dac_adc_test.o \
./UR_code/developer_code/tests\ src/flash_test.o \
./UR_code/developer_code/tests\ src/i2c_test.o \
./UR_code/developer_code/tests\ src/spi_test.o \
./UR_code/developer_code/tests\ src/uart_test.o 

C_DEPS += \
./UR_code/developer_code/tests\ src/dac_adc_test.d \
./UR_code/developer_code/tests\ src/flash_test.d \
./UR_code/developer_code/tests\ src/i2c_test.d \
./UR_code/developer_code/tests\ src/spi_test.d \
./UR_code/developer_code/tests\ src/uart_test.d 


# Each subdirectory must supply rules for building sources it contributes
UR_code/developer_code/tests\ src/dac_adc_test.o: ../UR_code/developer_code/tests\ src/dac_adc_test.c UR_code/developer_code/tests\ src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F746xx -c -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"UR_code/developer_code/tests src/dac_adc_test.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
UR_code/developer_code/tests\ src/flash_test.o: ../UR_code/developer_code/tests\ src/flash_test.c UR_code/developer_code/tests\ src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F746xx -c -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"UR_code/developer_code/tests src/flash_test.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
UR_code/developer_code/tests\ src/i2c_test.o: ../UR_code/developer_code/tests\ src/i2c_test.c UR_code/developer_code/tests\ src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F746xx -c -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"UR_code/developer_code/tests src/i2c_test.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
UR_code/developer_code/tests\ src/spi_test.o: ../UR_code/developer_code/tests\ src/spi_test.c UR_code/developer_code/tests\ src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F746xx -c -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"UR_code/developer_code/tests src/spi_test.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
UR_code/developer_code/tests\ src/uart_test.o: ../UR_code/developer_code/tests\ src/uart_test.c UR_code/developer_code/tests\ src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g -DDEBUG -DUSE_HAL_DRIVER -DSTM32F746xx -c -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I"C:/unit testing project/unit-test/unit testing stm side/UR_code/developer_code/tests inc" -I../Core/Inc -I../LWIP/App -I../LWIP/Target -I../Middlewares/Third_Party/LwIP/src/include -I../Middlewares/Third_Party/LwIP/system -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Drivers/BSP/Components/lan8742 -I../Middlewares/Third_Party/LwIP/src/include/netif/ppp -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Middlewares/Third_Party/LwIP/src/include/lwip -I../Middlewares/Third_Party/LwIP/src/include/lwip/apps -I../Middlewares/Third_Party/LwIP/src/include/lwip/priv -I../Middlewares/Third_Party/LwIP/src/include/lwip/prot -I../Middlewares/Third_Party/LwIP/src/include/netif -I../Middlewares/Third_Party/LwIP/src/include/compat/posix -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/arpa -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/net -I../Middlewares/Third_Party/LwIP/src/include/compat/posix/sys -I../Middlewares/Third_Party/LwIP/src/include/compat/stdc -I../Middlewares/Third_Party/LwIP/system/arch -I../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"UR_code/developer_code/tests src/uart_test.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-UR_code-2f-developer_code-2f-tests-20-src

clean-UR_code-2f-developer_code-2f-tests-20-src:
	-$(RM) ./UR_code/developer_code/tests\ src/dac_adc_test.cyclo ./UR_code/developer_code/tests\ src/dac_adc_test.d ./UR_code/developer_code/tests\ src/dac_adc_test.o ./UR_code/developer_code/tests\ src/dac_adc_test.su ./UR_code/developer_code/tests\ src/flash_test.cyclo ./UR_code/developer_code/tests\ src/flash_test.d ./UR_code/developer_code/tests\ src/flash_test.o ./UR_code/developer_code/tests\ src/flash_test.su ./UR_code/developer_code/tests\ src/i2c_test.cyclo ./UR_code/developer_code/tests\ src/i2c_test.d ./UR_code/developer_code/tests\ src/i2c_test.o ./UR_code/developer_code/tests\ src/i2c_test.su ./UR_code/developer_code/tests\ src/spi_test.cyclo ./UR_code/developer_code/tests\ src/spi_test.d ./UR_code/developer_code/tests\ src/spi_test.o ./UR_code/developer_code/tests\ src/spi_test.su ./UR_code/developer_code/tests\ src/uart_test.cyclo ./UR_code/developer_code/tests\ src/uart_test.d ./UR_code/developer_code/tests\ src/uart_test.o ./UR_code/developer_code/tests\ src/uart_test.su

.PHONY: clean-UR_code-2f-developer_code-2f-tests-20-src

